### ISSUE TITLE
data

### ISSUE THREAD

**Issue by newHellow** [lindsey98/SVM-HOG-object-detection#1]
Can you upload the dataset? I'm a foreigner. I can view the web.thanks.

**Comment by lindsey98** [comment]
Hi, thanks for your interest. Unfortunately, this repository is deprecated and no longer maintained. If you are interested you can refer to the original code here: https://github.com/SamPlvs/Object-detection-via-HOG-SVM. They do provide some test cases.

**Comment by newHellow** [comment]
OK！tanks！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lindsey98/SVM-HOG-object-detection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月3日(星期二) 中午12:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lindsey98/SVM-HOG-object-detection] data (Issue #1)





 
Hi, thanks for your interest. Unfortunately, this repository is deprecated and no longer maintained. If you are interested you can refer to the original code here: https://github.com/SamPlvs/Object-detection-via-HOG-SVM. They do provide some test cases.
